import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import ProviderTanstack from "@/components/tanstackProvider";


const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Riassunto youtube",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <ProviderTanstack>
          {children}
        </ProviderTanstack>
      </body>
    </html>
  );
}
